### ISSUE TITLE
More details about the two images?

### ISSUE THREAD

**Issue by brmarkus** [psimatis/QuadTree#2]
The README contains two very interesting examples

> The figures visualize partitions (i.e., leaves) for both strategies. Optimized Point Split is left and Region Split right. The dataset used is 1 million points of ships geolocations.

Can you still remember, how you have created those two images, where you got the dataset from, how you finally created the images?

**Comment by psimatis** [comment]
Hello!

The dataset was privately donated. It consists of tanker geolocations.
I plotted the leaf layer of the two quad trees. You can easily reproduce it for your dataset using the QuadTreeNode::isLeaf() function.

More details can be found on this VLDB paper: [https://www.vldb.org/pvldb/vol16/p670-moti.pdf](url)

**Comment by brmarkus** [comment]
Thank you very much, the paper is really interesting, will also have a closer look to the referenced repo "https://gitlab.com/moinmoti/waffle".
Congrats to you as an author of this great paper!
